### ISSUE TITLE
Alert user of duplicate projects

### ISSUE THREAD

**Issue by a-yun** [SwiftLaTeX/SwiftLaTeX#17]
Currently attempting to create a project whose name already exists fails silently and logs to console. It would be a nice UX improvement to alert the user when this happens.

https://github.com/SwiftLaTeX/SwiftLaTeX/blob/1c06311cb3b518b514c8491f81ae20af7a4fbf17/ide/js/index.js#L261

**Comment by elliott-wen** [comment]
Thanks for your valuable advice :) Already patched it.

**Comment by alerque** [comment]
Great to see the attention this project is attracting and that you're responding to issues! @Elliott.Wen I would seriously consider getting signed up for Github Sponsors if you are able to. It's not a magic cure-all for making development of OSS projects viable livelihood but it might help.

Also if this issue is patched already, it can be closed, no?

**Comment by elliott-wen** [comment]
> Great to see the attention this project is attracting and that you're responding to issues! @Elliott.Wen I would seriously consider getting signed up for Github Sponsors if you are able to. It's not a magic cure-all for making development of OSS projects viable livelihood but it might help.
> 
> Also if this issue is patched already, it can be closed, no?

Thanks :)
