### ISSUE TITLE
CORS access to mirror? 

### ISSUE THREAD

**Issue by gerrymanoim** [SwiftLaTeX/SwiftLaTeX#79]
I'm trying to deploy a very simple editor on a personal site (basically cloning https://www.swiftlatex.com/pdftex_basic.html to start) and I get issues whenever attempting to access the mirror sever: 

> Access to XMLHttpRequest at 'https://texlive2.swiftlatex.com/pdftex/10/swiftlatexpdftex.fmt' from origin '<my domain>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

1. Is that expected?
2. If so - what's the correct configuration to point switflatex to a different mirror? It looks like these might be hardcoded? https://github.com/SwiftLaTeX/SwiftLaTeX/blob/f39da903d162f1cae6a621862069a41a630790d6/pdftex.wasm/pre.js#L7

**Comment by adamkaplan0** [comment]
I'm not sure whether the SwiftLaTeX team wants others to use their backend server. To answer your questions, they changed the TeXLive endpoint address somewhat recently so the one you wrote above is no longer valid afaik.

If you want to run your own mirror, you can clone this project for the frontend and [this](https://github.com/SwiftLaTeX/Texlive-Ondemand) for the backend server. Since it is a docker container the setup is super easy and you can run it on a cheap VPS.

**Comment by feberts** [comment]
Well, there is the API function `setTexliveEndpoint(url: string)` to specify a different TeXLive endpoint address, but I could not get it to work. I ended up replacing the hardcoded URLs.

Does anybody know, how to use this function properly? When/where exactly do you call it?

**Comment by feberts** [comment]
You can use the API function `setTexliveEndpoint(url: string)` to specify a different TeXLive endpoint address. You should call it right after `loadEngine()`.

**Comment by elliott-wen** [comment]
Fixed the demo. Sorry for the delay
